/*
 * Petrolifera API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// UtilizadorPerfilSeguranca struct for UtilizadorPerfilSeguranca
type UtilizadorPerfilSeguranca struct {
	Id *int64 `json:"id,omitempty"`
	Deleted *int32 `json:"deleted,omitempty"`
	Upd NullableTime `json:"upd,omitempty"`
	Usr NullableInt64 `json:"usr,omitempty"`
	RefUtilizador NullableInt64 `json:"refUtilizador,omitempty"`
	RefPerfilSeguranca NullableInt64 `json:"refPerfilSeguranca,omitempty"`
	RefPerfilSegurancaNavigation *PerfilSeguranca `json:"refPerfilSegurancaNavigation,omitempty"`
	RefUtilizadorNavigation *Utilizador `json:"refUtilizadorNavigation,omitempty"`
}

// NewUtilizadorPerfilSeguranca instantiates a new UtilizadorPerfilSeguranca object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUtilizadorPerfilSeguranca() *UtilizadorPerfilSeguranca {
	this := UtilizadorPerfilSeguranca{}
	return &this
}

// NewUtilizadorPerfilSegurancaWithDefaults instantiates a new UtilizadorPerfilSeguranca object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUtilizadorPerfilSegurancaWithDefaults() *UtilizadorPerfilSeguranca {
	this := UtilizadorPerfilSeguranca{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UtilizadorPerfilSeguranca) GetId() int64 {
	if o == nil || o.Id == nil {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UtilizadorPerfilSeguranca) GetIdOk() (*int64, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UtilizadorPerfilSeguranca) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *UtilizadorPerfilSeguranca) SetId(v int64) {
	o.Id = &v
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *UtilizadorPerfilSeguranca) GetDeleted() int32 {
	if o == nil || o.Deleted == nil {
		var ret int32
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UtilizadorPerfilSeguranca) GetDeletedOk() (*int32, bool) {
	if o == nil || o.Deleted == nil {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *UtilizadorPerfilSeguranca) HasDeleted() bool {
	if o != nil && o.Deleted != nil {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given int32 and assigns it to the Deleted field.
func (o *UtilizadorPerfilSeguranca) SetDeleted(v int32) {
	o.Deleted = &v
}

// GetUpd returns the Upd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UtilizadorPerfilSeguranca) GetUpd() time.Time {
	if o == nil || o.Upd.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.Upd.Get()
}

// GetUpdOk returns a tuple with the Upd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UtilizadorPerfilSeguranca) GetUpdOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Upd.Get(), o.Upd.IsSet()
}

// HasUpd returns a boolean if a field has been set.
func (o *UtilizadorPerfilSeguranca) HasUpd() bool {
	if o != nil && o.Upd.IsSet() {
		return true
	}

	return false
}

// SetUpd gets a reference to the given NullableTime and assigns it to the Upd field.
func (o *UtilizadorPerfilSeguranca) SetUpd(v time.Time) {
	o.Upd.Set(&v)
}
// SetUpdNil sets the value for Upd to be an explicit nil
func (o *UtilizadorPerfilSeguranca) SetUpdNil() {
	o.Upd.Set(nil)
}

// UnsetUpd ensures that no value is present for Upd, not even an explicit nil
func (o *UtilizadorPerfilSeguranca) UnsetUpd() {
	o.Upd.Unset()
}

// GetUsr returns the Usr field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UtilizadorPerfilSeguranca) GetUsr() int64 {
	if o == nil || o.Usr.Get() == nil {
		var ret int64
		return ret
	}
	return *o.Usr.Get()
}

// GetUsrOk returns a tuple with the Usr field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UtilizadorPerfilSeguranca) GetUsrOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Usr.Get(), o.Usr.IsSet()
}

// HasUsr returns a boolean if a field has been set.
func (o *UtilizadorPerfilSeguranca) HasUsr() bool {
	if o != nil && o.Usr.IsSet() {
		return true
	}

	return false
}

// SetUsr gets a reference to the given NullableInt64 and assigns it to the Usr field.
func (o *UtilizadorPerfilSeguranca) SetUsr(v int64) {
	o.Usr.Set(&v)
}
// SetUsrNil sets the value for Usr to be an explicit nil
func (o *UtilizadorPerfilSeguranca) SetUsrNil() {
	o.Usr.Set(nil)
}

// UnsetUsr ensures that no value is present for Usr, not even an explicit nil
func (o *UtilizadorPerfilSeguranca) UnsetUsr() {
	o.Usr.Unset()
}

// GetRefUtilizador returns the RefUtilizador field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UtilizadorPerfilSeguranca) GetRefUtilizador() int64 {
	if o == nil || o.RefUtilizador.Get() == nil {
		var ret int64
		return ret
	}
	return *o.RefUtilizador.Get()
}

// GetRefUtilizadorOk returns a tuple with the RefUtilizador field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UtilizadorPerfilSeguranca) GetRefUtilizadorOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RefUtilizador.Get(), o.RefUtilizador.IsSet()
}

// HasRefUtilizador returns a boolean if a field has been set.
func (o *UtilizadorPerfilSeguranca) HasRefUtilizador() bool {
	if o != nil && o.RefUtilizador.IsSet() {
		return true
	}

	return false
}

// SetRefUtilizador gets a reference to the given NullableInt64 and assigns it to the RefUtilizador field.
func (o *UtilizadorPerfilSeguranca) SetRefUtilizador(v int64) {
	o.RefUtilizador.Set(&v)
}
// SetRefUtilizadorNil sets the value for RefUtilizador to be an explicit nil
func (o *UtilizadorPerfilSeguranca) SetRefUtilizadorNil() {
	o.RefUtilizador.Set(nil)
}

// UnsetRefUtilizador ensures that no value is present for RefUtilizador, not even an explicit nil
func (o *UtilizadorPerfilSeguranca) UnsetRefUtilizador() {
	o.RefUtilizador.Unset()
}

// GetRefPerfilSeguranca returns the RefPerfilSeguranca field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UtilizadorPerfilSeguranca) GetRefPerfilSeguranca() int64 {
	if o == nil || o.RefPerfilSeguranca.Get() == nil {
		var ret int64
		return ret
	}
	return *o.RefPerfilSeguranca.Get()
}

// GetRefPerfilSegurancaOk returns a tuple with the RefPerfilSeguranca field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UtilizadorPerfilSeguranca) GetRefPerfilSegurancaOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RefPerfilSeguranca.Get(), o.RefPerfilSeguranca.IsSet()
}

// HasRefPerfilSeguranca returns a boolean if a field has been set.
func (o *UtilizadorPerfilSeguranca) HasRefPerfilSeguranca() bool {
	if o != nil && o.RefPerfilSeguranca.IsSet() {
		return true
	}

	return false
}

// SetRefPerfilSeguranca gets a reference to the given NullableInt64 and assigns it to the RefPerfilSeguranca field.
func (o *UtilizadorPerfilSeguranca) SetRefPerfilSeguranca(v int64) {
	o.RefPerfilSeguranca.Set(&v)
}
// SetRefPerfilSegurancaNil sets the value for RefPerfilSeguranca to be an explicit nil
func (o *UtilizadorPerfilSeguranca) SetRefPerfilSegurancaNil() {
	o.RefPerfilSeguranca.Set(nil)
}

// UnsetRefPerfilSeguranca ensures that no value is present for RefPerfilSeguranca, not even an explicit nil
func (o *UtilizadorPerfilSeguranca) UnsetRefPerfilSeguranca() {
	o.RefPerfilSeguranca.Unset()
}

// GetRefPerfilSegurancaNavigation returns the RefPerfilSegurancaNavigation field value if set, zero value otherwise.
func (o *UtilizadorPerfilSeguranca) GetRefPerfilSegurancaNavigation() PerfilSeguranca {
	if o == nil || o.RefPerfilSegurancaNavigation == nil {
		var ret PerfilSeguranca
		return ret
	}
	return *o.RefPerfilSegurancaNavigation
}

// GetRefPerfilSegurancaNavigationOk returns a tuple with the RefPerfilSegurancaNavigation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UtilizadorPerfilSeguranca) GetRefPerfilSegurancaNavigationOk() (*PerfilSeguranca, bool) {
	if o == nil || o.RefPerfilSegurancaNavigation == nil {
		return nil, false
	}
	return o.RefPerfilSegurancaNavigation, true
}

// HasRefPerfilSegurancaNavigation returns a boolean if a field has been set.
func (o *UtilizadorPerfilSeguranca) HasRefPerfilSegurancaNavigation() bool {
	if o != nil && o.RefPerfilSegurancaNavigation != nil {
		return true
	}

	return false
}

// SetRefPerfilSegurancaNavigation gets a reference to the given PerfilSeguranca and assigns it to the RefPerfilSegurancaNavigation field.
func (o *UtilizadorPerfilSeguranca) SetRefPerfilSegurancaNavigation(v PerfilSeguranca) {
	o.RefPerfilSegurancaNavigation = &v
}

// GetRefUtilizadorNavigation returns the RefUtilizadorNavigation field value if set, zero value otherwise.
func (o *UtilizadorPerfilSeguranca) GetRefUtilizadorNavigation() Utilizador {
	if o == nil || o.RefUtilizadorNavigation == nil {
		var ret Utilizador
		return ret
	}
	return *o.RefUtilizadorNavigation
}

// GetRefUtilizadorNavigationOk returns a tuple with the RefUtilizadorNavigation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UtilizadorPerfilSeguranca) GetRefUtilizadorNavigationOk() (*Utilizador, bool) {
	if o == nil || o.RefUtilizadorNavigation == nil {
		return nil, false
	}
	return o.RefUtilizadorNavigation, true
}

// HasRefUtilizadorNavigation returns a boolean if a field has been set.
func (o *UtilizadorPerfilSeguranca) HasRefUtilizadorNavigation() bool {
	if o != nil && o.RefUtilizadorNavigation != nil {
		return true
	}

	return false
}

// SetRefUtilizadorNavigation gets a reference to the given Utilizador and assigns it to the RefUtilizadorNavigation field.
func (o *UtilizadorPerfilSeguranca) SetRefUtilizadorNavigation(v Utilizador) {
	o.RefUtilizadorNavigation = &v
}

func (o UtilizadorPerfilSeguranca) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Deleted != nil {
		toSerialize["deleted"] = o.Deleted
	}
	if o.Upd.IsSet() {
		toSerialize["upd"] = o.Upd.Get()
	}
	if o.Usr.IsSet() {
		toSerialize["usr"] = o.Usr.Get()
	}
	if o.RefUtilizador.IsSet() {
		toSerialize["refUtilizador"] = o.RefUtilizador.Get()
	}
	if o.RefPerfilSeguranca.IsSet() {
		toSerialize["refPerfilSeguranca"] = o.RefPerfilSeguranca.Get()
	}
	if o.RefPerfilSegurancaNavigation != nil {
		toSerialize["refPerfilSegurancaNavigation"] = o.RefPerfilSegurancaNavigation
	}
	if o.RefUtilizadorNavigation != nil {
		toSerialize["refUtilizadorNavigation"] = o.RefUtilizadorNavigation
	}
	return json.Marshal(toSerialize)
}

type NullableUtilizadorPerfilSeguranca struct {
	value *UtilizadorPerfilSeguranca
	isSet bool
}

func (v NullableUtilizadorPerfilSeguranca) Get() *UtilizadorPerfilSeguranca {
	return v.value
}

func (v *NullableUtilizadorPerfilSeguranca) Set(val *UtilizadorPerfilSeguranca) {
	v.value = val
	v.isSet = true
}

func (v NullableUtilizadorPerfilSeguranca) IsSet() bool {
	return v.isSet
}

func (v *NullableUtilizadorPerfilSeguranca) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUtilizadorPerfilSeguranca(val *UtilizadorPerfilSeguranca) *NullableUtilizadorPerfilSeguranca {
	return &NullableUtilizadorPerfilSeguranca{value: val, isSet: true}
}

func (v NullableUtilizadorPerfilSeguranca) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUtilizadorPerfilSeguranca) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


