/*
 * Petrolifera API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// TipoRede the model 'TipoRede'
type TipoRede int32


var allowedTipoRedeEnumValues = []TipoRede{
	0,
	1,
	2,
	3,
}

func (v *TipoRede) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TipoRede(value)
	for _, existing := range allowedTipoRedeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TipoRede", value)
}

// NewTipoRedeFromValue returns a pointer to a valid TipoRede
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTipoRedeFromValue(v int32) (*TipoRede, error) {
	ev := TipoRede(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TipoRede: valid values are %v", v, allowedTipoRedeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TipoRede) IsValid() bool {
	for _, existing := range allowedTipoRedeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TipoRede value
func (v TipoRede) Ptr() *TipoRede {
	return &v
}

type NullableTipoRede struct {
	value *TipoRede
	isSet bool
}

func (v NullableTipoRede) Get() *TipoRede {
	return v.value
}

func (v *NullableTipoRede) Set(val *TipoRede) {
	v.value = val
	v.isSet = true
}

func (v NullableTipoRede) IsSet() bool {
	return v.isSet
}

func (v *NullableTipoRede) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTipoRede(val *TipoRede) *NullableTipoRede {
	return &NullableTipoRede{value: val, isSet: true}
}

func (v NullableTipoRede) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTipoRede) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

