/*
 * Petrolifera API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// EstadoGvm the model 'EstadoGvm'
type EstadoGvm int32


var allowedEstadoGvmEnumValues = []EstadoGvm{
	0,
	1,
	2,
}

func (v *EstadoGvm) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EstadoGvm(value)
	for _, existing := range allowedEstadoGvmEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EstadoGvm", value)
}

// NewEstadoGvmFromValue returns a pointer to a valid EstadoGvm
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEstadoGvmFromValue(v int32) (*EstadoGvm, error) {
	ev := EstadoGvm(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EstadoGvm: valid values are %v", v, allowedEstadoGvmEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EstadoGvm) IsValid() bool {
	for _, existing := range allowedEstadoGvmEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EstadoGvm value
func (v EstadoGvm) Ptr() *EstadoGvm {
	return &v
}

type NullableEstadoGvm struct {
	value *EstadoGvm
	isSet bool
}

func (v NullableEstadoGvm) Get() *EstadoGvm {
	return v.value
}

func (v *NullableEstadoGvm) Set(val *EstadoGvm) {
	v.value = val
	v.isSet = true
}

func (v NullableEstadoGvm) IsSet() bool {
	return v.isSet
}

func (v *NullableEstadoGvm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEstadoGvm(val *EstadoGvm) *NullableEstadoGvm {
	return &NullableEstadoGvm{value: val, isSet: true}
}

func (v NullableEstadoGvm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEstadoGvm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

