/*
 * Petrolifera API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// EstadosOrdemServico the model 'EstadosOrdemServico'
type EstadosOrdemServico int32

// List of EstadosOrdemServico


var allowedEstadosOrdemServicoEnumValues = []EstadosOrdemServico{
	0,
	1,
	2,
}

func (v *EstadosOrdemServico) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EstadosOrdemServico(value)
	for _, existing := range allowedEstadosOrdemServicoEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EstadosOrdemServico", value)
}

// NewEstadosOrdemServicoFromValue returns a pointer to a valid EstadosOrdemServico
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEstadosOrdemServicoFromValue(v int32) (*EstadosOrdemServico, error) {
	ev := EstadosOrdemServico(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EstadosOrdemServico: valid values are %v", v, allowedEstadosOrdemServicoEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EstadosOrdemServico) IsValid() bool {
	for _, existing := range allowedEstadosOrdemServicoEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EstadosOrdemServico value
func (v EstadosOrdemServico) Ptr() *EstadosOrdemServico {
	return &v
}

type NullableEstadosOrdemServico struct {
	value *EstadosOrdemServico
	isSet bool
}

func (v NullableEstadosOrdemServico) Get() *EstadosOrdemServico {
	return v.value
}

func (v *NullableEstadosOrdemServico) Set(val *EstadosOrdemServico) {
	v.value = val
	v.isSet = true
}

func (v NullableEstadosOrdemServico) IsSet() bool {
	return v.isSet
}

func (v *NullableEstadosOrdemServico) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEstadosOrdemServico(val *EstadosOrdemServico) *NullableEstadosOrdemServico {
	return &NullableEstadosOrdemServico{value: val, isSet: true}
}

func (v NullableEstadosOrdemServico) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEstadosOrdemServico) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

