/*
 * Petrolifera API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// TipoOrigem the model 'TipoOrigem'
type TipoOrigem int32

// List of TipoOrigem
const (
	_0 TipoOrigem = 0
	_1 TipoOrigem = 1
)

var allowedTipoOrigemEnumValues = []TipoOrigem{
	0,
	1,
}

func (v *TipoOrigem) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TipoOrigem(value)
	for _, existing := range allowedTipoOrigemEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TipoOrigem", value)
}

// NewTipoOrigemFromValue returns a pointer to a valid TipoOrigem
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTipoOrigemFromValue(v int32) (*TipoOrigem, error) {
	ev := TipoOrigem(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TipoOrigem: valid values are %v", v, allowedTipoOrigemEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TipoOrigem) IsValid() bool {
	for _, existing := range allowedTipoOrigemEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TipoOrigem value
func (v TipoOrigem) Ptr() *TipoOrigem {
	return &v
}

type NullableTipoOrigem struct {
	value *TipoOrigem
	isSet bool
}

func (v NullableTipoOrigem) Get() *TipoOrigem {
	return v.value
}

func (v *NullableTipoOrigem) Set(val *TipoOrigem) {
	v.value = val
	v.isSet = true
}

func (v NullableTipoOrigem) IsSet() bool {
	return v.isSet
}

func (v *NullableTipoOrigem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTipoOrigem(val *TipoOrigem) *NullableTipoOrigem {
	return &NullableTipoOrigem{value: val, isSet: true}
}

func (v NullableTipoOrigem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTipoOrigem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

