/*
 * Petrolifera API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// LocalDTO struct for LocalDTO
type LocalDTO struct {
	Id *int64 `json:"id,omitempty"`
	Nome NullableString `json:"nome,omitempty"`
	Morada NullableString `json:"morada,omitempty"`
	RefAssistencia NullableInt64 `json:"refAssistencia,omitempty"`
	RefGestorTecnico NullableInt64 `json:"refGestorTecnico,omitempty"`
	RefReposicao NullableInt64 `json:"refReposicao,omitempty"`
	RefGestorReposicao NullableInt64 `json:"refGestorReposicao,omitempty"`
	Latitude NullableString `json:"latitude,omitempty"`
	Longitude NullableString `json:"longitude,omitempty"`
}

// NewLocalDTO instantiates a new LocalDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocalDTO() *LocalDTO {
	this := LocalDTO{}
	return &this
}

// NewLocalDTOWithDefaults instantiates a new LocalDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocalDTOWithDefaults() *LocalDTO {
	this := LocalDTO{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *LocalDTO) GetId() int64 {
	if o == nil || o.Id == nil {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocalDTO) GetIdOk() (*int64, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *LocalDTO) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *LocalDTO) SetId(v int64) {
	o.Id = &v
}

// GetNome returns the Nome field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LocalDTO) GetNome() string {
	if o == nil || o.Nome.Get() == nil {
		var ret string
		return ret
	}
	return *o.Nome.Get()
}

// GetNomeOk returns a tuple with the Nome field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LocalDTO) GetNomeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Nome.Get(), o.Nome.IsSet()
}

// HasNome returns a boolean if a field has been set.
func (o *LocalDTO) HasNome() bool {
	if o != nil && o.Nome.IsSet() {
		return true
	}

	return false
}

// SetNome gets a reference to the given NullableString and assigns it to the Nome field.
func (o *LocalDTO) SetNome(v string) {
	o.Nome.Set(&v)
}
// SetNomeNil sets the value for Nome to be an explicit nil
func (o *LocalDTO) SetNomeNil() {
	o.Nome.Set(nil)
}

// UnsetNome ensures that no value is present for Nome, not even an explicit nil
func (o *LocalDTO) UnsetNome() {
	o.Nome.Unset()
}

// GetMorada returns the Morada field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LocalDTO) GetMorada() string {
	if o == nil || o.Morada.Get() == nil {
		var ret string
		return ret
	}
	return *o.Morada.Get()
}

// GetMoradaOk returns a tuple with the Morada field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LocalDTO) GetMoradaOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Morada.Get(), o.Morada.IsSet()
}

// HasMorada returns a boolean if a field has been set.
func (o *LocalDTO) HasMorada() bool {
	if o != nil && o.Morada.IsSet() {
		return true
	}

	return false
}

// SetMorada gets a reference to the given NullableString and assigns it to the Morada field.
func (o *LocalDTO) SetMorada(v string) {
	o.Morada.Set(&v)
}
// SetMoradaNil sets the value for Morada to be an explicit nil
func (o *LocalDTO) SetMoradaNil() {
	o.Morada.Set(nil)
}

// UnsetMorada ensures that no value is present for Morada, not even an explicit nil
func (o *LocalDTO) UnsetMorada() {
	o.Morada.Unset()
}

// GetRefAssistencia returns the RefAssistencia field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LocalDTO) GetRefAssistencia() int64 {
	if o == nil || o.RefAssistencia.Get() == nil {
		var ret int64
		return ret
	}
	return *o.RefAssistencia.Get()
}

// GetRefAssistenciaOk returns a tuple with the RefAssistencia field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LocalDTO) GetRefAssistenciaOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RefAssistencia.Get(), o.RefAssistencia.IsSet()
}

// HasRefAssistencia returns a boolean if a field has been set.
func (o *LocalDTO) HasRefAssistencia() bool {
	if o != nil && o.RefAssistencia.IsSet() {
		return true
	}

	return false
}

// SetRefAssistencia gets a reference to the given NullableInt64 and assigns it to the RefAssistencia field.
func (o *LocalDTO) SetRefAssistencia(v int64) {
	o.RefAssistencia.Set(&v)
}
// SetRefAssistenciaNil sets the value for RefAssistencia to be an explicit nil
func (o *LocalDTO) SetRefAssistenciaNil() {
	o.RefAssistencia.Set(nil)
}

// UnsetRefAssistencia ensures that no value is present for RefAssistencia, not even an explicit nil
func (o *LocalDTO) UnsetRefAssistencia() {
	o.RefAssistencia.Unset()
}

// GetRefGestorTecnico returns the RefGestorTecnico field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LocalDTO) GetRefGestorTecnico() int64 {
	if o == nil || o.RefGestorTecnico.Get() == nil {
		var ret int64
		return ret
	}
	return *o.RefGestorTecnico.Get()
}

// GetRefGestorTecnicoOk returns a tuple with the RefGestorTecnico field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LocalDTO) GetRefGestorTecnicoOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RefGestorTecnico.Get(), o.RefGestorTecnico.IsSet()
}

// HasRefGestorTecnico returns a boolean if a field has been set.
func (o *LocalDTO) HasRefGestorTecnico() bool {
	if o != nil && o.RefGestorTecnico.IsSet() {
		return true
	}

	return false
}

// SetRefGestorTecnico gets a reference to the given NullableInt64 and assigns it to the RefGestorTecnico field.
func (o *LocalDTO) SetRefGestorTecnico(v int64) {
	o.RefGestorTecnico.Set(&v)
}
// SetRefGestorTecnicoNil sets the value for RefGestorTecnico to be an explicit nil
func (o *LocalDTO) SetRefGestorTecnicoNil() {
	o.RefGestorTecnico.Set(nil)
}

// UnsetRefGestorTecnico ensures that no value is present for RefGestorTecnico, not even an explicit nil
func (o *LocalDTO) UnsetRefGestorTecnico() {
	o.RefGestorTecnico.Unset()
}

// GetRefReposicao returns the RefReposicao field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LocalDTO) GetRefReposicao() int64 {
	if o == nil || o.RefReposicao.Get() == nil {
		var ret int64
		return ret
	}
	return *o.RefReposicao.Get()
}

// GetRefReposicaoOk returns a tuple with the RefReposicao field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LocalDTO) GetRefReposicaoOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RefReposicao.Get(), o.RefReposicao.IsSet()
}

// HasRefReposicao returns a boolean if a field has been set.
func (o *LocalDTO) HasRefReposicao() bool {
	if o != nil && o.RefReposicao.IsSet() {
		return true
	}

	return false
}

// SetRefReposicao gets a reference to the given NullableInt64 and assigns it to the RefReposicao field.
func (o *LocalDTO) SetRefReposicao(v int64) {
	o.RefReposicao.Set(&v)
}
// SetRefReposicaoNil sets the value for RefReposicao to be an explicit nil
func (o *LocalDTO) SetRefReposicaoNil() {
	o.RefReposicao.Set(nil)
}

// UnsetRefReposicao ensures that no value is present for RefReposicao, not even an explicit nil
func (o *LocalDTO) UnsetRefReposicao() {
	o.RefReposicao.Unset()
}

// GetRefGestorReposicao returns the RefGestorReposicao field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LocalDTO) GetRefGestorReposicao() int64 {
	if o == nil || o.RefGestorReposicao.Get() == nil {
		var ret int64
		return ret
	}
	return *o.RefGestorReposicao.Get()
}

// GetRefGestorReposicaoOk returns a tuple with the RefGestorReposicao field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LocalDTO) GetRefGestorReposicaoOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RefGestorReposicao.Get(), o.RefGestorReposicao.IsSet()
}

// HasRefGestorReposicao returns a boolean if a field has been set.
func (o *LocalDTO) HasRefGestorReposicao() bool {
	if o != nil && o.RefGestorReposicao.IsSet() {
		return true
	}

	return false
}

// SetRefGestorReposicao gets a reference to the given NullableInt64 and assigns it to the RefGestorReposicao field.
func (o *LocalDTO) SetRefGestorReposicao(v int64) {
	o.RefGestorReposicao.Set(&v)
}
// SetRefGestorReposicaoNil sets the value for RefGestorReposicao to be an explicit nil
func (o *LocalDTO) SetRefGestorReposicaoNil() {
	o.RefGestorReposicao.Set(nil)
}

// UnsetRefGestorReposicao ensures that no value is present for RefGestorReposicao, not even an explicit nil
func (o *LocalDTO) UnsetRefGestorReposicao() {
	o.RefGestorReposicao.Unset()
}

// GetLatitude returns the Latitude field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LocalDTO) GetLatitude() string {
	if o == nil || o.Latitude.Get() == nil {
		var ret string
		return ret
	}
	return *o.Latitude.Get()
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LocalDTO) GetLatitudeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Latitude.Get(), o.Latitude.IsSet()
}

// HasLatitude returns a boolean if a field has been set.
func (o *LocalDTO) HasLatitude() bool {
	if o != nil && o.Latitude.IsSet() {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given NullableString and assigns it to the Latitude field.
func (o *LocalDTO) SetLatitude(v string) {
	o.Latitude.Set(&v)
}
// SetLatitudeNil sets the value for Latitude to be an explicit nil
func (o *LocalDTO) SetLatitudeNil() {
	o.Latitude.Set(nil)
}

// UnsetLatitude ensures that no value is present for Latitude, not even an explicit nil
func (o *LocalDTO) UnsetLatitude() {
	o.Latitude.Unset()
}

// GetLongitude returns the Longitude field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LocalDTO) GetLongitude() string {
	if o == nil || o.Longitude.Get() == nil {
		var ret string
		return ret
	}
	return *o.Longitude.Get()
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LocalDTO) GetLongitudeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Longitude.Get(), o.Longitude.IsSet()
}

// HasLongitude returns a boolean if a field has been set.
func (o *LocalDTO) HasLongitude() bool {
	if o != nil && o.Longitude.IsSet() {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given NullableString and assigns it to the Longitude field.
func (o *LocalDTO) SetLongitude(v string) {
	o.Longitude.Set(&v)
}
// SetLongitudeNil sets the value for Longitude to be an explicit nil
func (o *LocalDTO) SetLongitudeNil() {
	o.Longitude.Set(nil)
}

// UnsetLongitude ensures that no value is present for Longitude, not even an explicit nil
func (o *LocalDTO) UnsetLongitude() {
	o.Longitude.Unset()
}

func (o LocalDTO) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Nome.IsSet() {
		toSerialize["nome"] = o.Nome.Get()
	}
	if o.Morada.IsSet() {
		toSerialize["morada"] = o.Morada.Get()
	}
	if o.RefAssistencia.IsSet() {
		toSerialize["refAssistencia"] = o.RefAssistencia.Get()
	}
	if o.RefGestorTecnico.IsSet() {
		toSerialize["refGestorTecnico"] = o.RefGestorTecnico.Get()
	}
	if o.RefReposicao.IsSet() {
		toSerialize["refReposicao"] = o.RefReposicao.Get()
	}
	if o.RefGestorReposicao.IsSet() {
		toSerialize["refGestorReposicao"] = o.RefGestorReposicao.Get()
	}
	if o.Latitude.IsSet() {
		toSerialize["latitude"] = o.Latitude.Get()
	}
	if o.Longitude.IsSet() {
		toSerialize["longitude"] = o.Longitude.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableLocalDTO struct {
	value *LocalDTO
	isSet bool
}

func (v NullableLocalDTO) Get() *LocalDTO {
	return v.value
}

func (v *NullableLocalDTO) Set(val *LocalDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableLocalDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableLocalDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocalDTO(val *LocalDTO) *NullableLocalDTO {
	return &NullableLocalDTO{value: val, isSet: true}
}

func (v NullableLocalDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocalDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


