/*
 * Petrolifera API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// EstadoNotificacao the model 'EstadoNotificacao'
type EstadoNotificacao int32

// List of EstadoNotificacao


var allowedEstadoNotificacaoEnumValues = []EstadoNotificacao{
	0,
	1,
	2,
}

func (v *EstadoNotificacao) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EstadoNotificacao(value)
	for _, existing := range allowedEstadoNotificacaoEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EstadoNotificacao", value)
}

// NewEstadoNotificacaoFromValue returns a pointer to a valid EstadoNotificacao
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEstadoNotificacaoFromValue(v int32) (*EstadoNotificacao, error) {
	ev := EstadoNotificacao(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EstadoNotificacao: valid values are %v", v, allowedEstadoNotificacaoEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EstadoNotificacao) IsValid() bool {
	for _, existing := range allowedEstadoNotificacaoEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EstadoNotificacao value
func (v EstadoNotificacao) Ptr() *EstadoNotificacao {
	return &v
}

type NullableEstadoNotificacao struct {
	value *EstadoNotificacao
	isSet bool
}

func (v NullableEstadoNotificacao) Get() *EstadoNotificacao {
	return v.value
}

func (v *NullableEstadoNotificacao) Set(val *EstadoNotificacao) {
	v.value = val
	v.isSet = true
}

func (v NullableEstadoNotificacao) IsSet() bool {
	return v.isSet
}

func (v *NullableEstadoNotificacao) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEstadoNotificacao(val *EstadoNotificacao) *NullableEstadoNotificacao {
	return &NullableEstadoNotificacao{value: val, isSet: true}
}

func (v NullableEstadoNotificacao) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEstadoNotificacao) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

