/*
 * Petrolifera API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// GvmDTO struct for GvmDTO
type GvmDTO struct {
	Id *int64 `json:"id,omitempty"`
	Nome NullableString `json:"nome,omitempty"`
	Modelo NullableString `json:"modelo,omitempty"`
	NumeroSerie NullableString `json:"numeroSerie,omitempty"`
	DataProducao NullableTime `json:"dataProducao,omitempty"`
	VersaoFirmware NullableString `json:"versaoFirmware,omitempty"`
	VersaoSoftware NullableString `json:"versaoSoftware,omitempty"`
	UltimaComunicacao NullableTime `json:"ultimaComunicacao,omitempty"`
	RefLocal NullableInt64 `json:"refLocal,omitempty"`
	RefEntidade NullableInt64 `json:"refEntidade,omitempty"`
	RefNo NullableInt64 `json:"refNo,omitempty"`
	Latitude NullableString `json:"latitude,omitempty"`
	Longitude NullableString `json:"longitude,omitempty"`
	Compartimentos []CompartimentoDTO `json:"compartimentos,omitempty"`
	CompartimentosProduto []ProdutoDTO `json:"compartimentosProduto,omitempty"`
}

// NewGvmDTO instantiates a new GvmDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGvmDTO() *GvmDTO {
	this := GvmDTO{}
	return &this
}

// NewGvmDTOWithDefaults instantiates a new GvmDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGvmDTOWithDefaults() *GvmDTO {
	this := GvmDTO{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GvmDTO) GetId() int64 {
	if o == nil || o.Id == nil {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GvmDTO) GetIdOk() (*int64, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GvmDTO) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *GvmDTO) SetId(v int64) {
	o.Id = &v
}

// GetNome returns the Nome field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmDTO) GetNome() string {
	if o == nil || o.Nome.Get() == nil {
		var ret string
		return ret
	}
	return *o.Nome.Get()
}

// GetNomeOk returns a tuple with the Nome field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmDTO) GetNomeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Nome.Get(), o.Nome.IsSet()
}

// HasNome returns a boolean if a field has been set.
func (o *GvmDTO) HasNome() bool {
	if o != nil && o.Nome.IsSet() {
		return true
	}

	return false
}

// SetNome gets a reference to the given NullableString and assigns it to the Nome field.
func (o *GvmDTO) SetNome(v string) {
	o.Nome.Set(&v)
}
// SetNomeNil sets the value for Nome to be an explicit nil
func (o *GvmDTO) SetNomeNil() {
	o.Nome.Set(nil)
}

// UnsetNome ensures that no value is present for Nome, not even an explicit nil
func (o *GvmDTO) UnsetNome() {
	o.Nome.Unset()
}

// GetModelo returns the Modelo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmDTO) GetModelo() string {
	if o == nil || o.Modelo.Get() == nil {
		var ret string
		return ret
	}
	return *o.Modelo.Get()
}

// GetModeloOk returns a tuple with the Modelo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmDTO) GetModeloOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Modelo.Get(), o.Modelo.IsSet()
}

// HasModelo returns a boolean if a field has been set.
func (o *GvmDTO) HasModelo() bool {
	if o != nil && o.Modelo.IsSet() {
		return true
	}

	return false
}

// SetModelo gets a reference to the given NullableString and assigns it to the Modelo field.
func (o *GvmDTO) SetModelo(v string) {
	o.Modelo.Set(&v)
}
// SetModeloNil sets the value for Modelo to be an explicit nil
func (o *GvmDTO) SetModeloNil() {
	o.Modelo.Set(nil)
}

// UnsetModelo ensures that no value is present for Modelo, not even an explicit nil
func (o *GvmDTO) UnsetModelo() {
	o.Modelo.Unset()
}

// GetNumeroSerie returns the NumeroSerie field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmDTO) GetNumeroSerie() string {
	if o == nil || o.NumeroSerie.Get() == nil {
		var ret string
		return ret
	}
	return *o.NumeroSerie.Get()
}

// GetNumeroSerieOk returns a tuple with the NumeroSerie field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmDTO) GetNumeroSerieOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.NumeroSerie.Get(), o.NumeroSerie.IsSet()
}

// HasNumeroSerie returns a boolean if a field has been set.
func (o *GvmDTO) HasNumeroSerie() bool {
	if o != nil && o.NumeroSerie.IsSet() {
		return true
	}

	return false
}

// SetNumeroSerie gets a reference to the given NullableString and assigns it to the NumeroSerie field.
func (o *GvmDTO) SetNumeroSerie(v string) {
	o.NumeroSerie.Set(&v)
}
// SetNumeroSerieNil sets the value for NumeroSerie to be an explicit nil
func (o *GvmDTO) SetNumeroSerieNil() {
	o.NumeroSerie.Set(nil)
}

// UnsetNumeroSerie ensures that no value is present for NumeroSerie, not even an explicit nil
func (o *GvmDTO) UnsetNumeroSerie() {
	o.NumeroSerie.Unset()
}

// GetDataProducao returns the DataProducao field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmDTO) GetDataProducao() time.Time {
	if o == nil || o.DataProducao.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.DataProducao.Get()
}

// GetDataProducaoOk returns a tuple with the DataProducao field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmDTO) GetDataProducaoOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.DataProducao.Get(), o.DataProducao.IsSet()
}

// HasDataProducao returns a boolean if a field has been set.
func (o *GvmDTO) HasDataProducao() bool {
	if o != nil && o.DataProducao.IsSet() {
		return true
	}

	return false
}

// SetDataProducao gets a reference to the given NullableTime and assigns it to the DataProducao field.
func (o *GvmDTO) SetDataProducao(v time.Time) {
	o.DataProducao.Set(&v)
}
// SetDataProducaoNil sets the value for DataProducao to be an explicit nil
func (o *GvmDTO) SetDataProducaoNil() {
	o.DataProducao.Set(nil)
}

// UnsetDataProducao ensures that no value is present for DataProducao, not even an explicit nil
func (o *GvmDTO) UnsetDataProducao() {
	o.DataProducao.Unset()
}

// GetVersaoFirmware returns the VersaoFirmware field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmDTO) GetVersaoFirmware() string {
	if o == nil || o.VersaoFirmware.Get() == nil {
		var ret string
		return ret
	}
	return *o.VersaoFirmware.Get()
}

// GetVersaoFirmwareOk returns a tuple with the VersaoFirmware field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmDTO) GetVersaoFirmwareOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.VersaoFirmware.Get(), o.VersaoFirmware.IsSet()
}

// HasVersaoFirmware returns a boolean if a field has been set.
func (o *GvmDTO) HasVersaoFirmware() bool {
	if o != nil && o.VersaoFirmware.IsSet() {
		return true
	}

	return false
}

// SetVersaoFirmware gets a reference to the given NullableString and assigns it to the VersaoFirmware field.
func (o *GvmDTO) SetVersaoFirmware(v string) {
	o.VersaoFirmware.Set(&v)
}
// SetVersaoFirmwareNil sets the value for VersaoFirmware to be an explicit nil
func (o *GvmDTO) SetVersaoFirmwareNil() {
	o.VersaoFirmware.Set(nil)
}

// UnsetVersaoFirmware ensures that no value is present for VersaoFirmware, not even an explicit nil
func (o *GvmDTO) UnsetVersaoFirmware() {
	o.VersaoFirmware.Unset()
}

// GetVersaoSoftware returns the VersaoSoftware field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmDTO) GetVersaoSoftware() string {
	if o == nil || o.VersaoSoftware.Get() == nil {
		var ret string
		return ret
	}
	return *o.VersaoSoftware.Get()
}

// GetVersaoSoftwareOk returns a tuple with the VersaoSoftware field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmDTO) GetVersaoSoftwareOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.VersaoSoftware.Get(), o.VersaoSoftware.IsSet()
}

// HasVersaoSoftware returns a boolean if a field has been set.
func (o *GvmDTO) HasVersaoSoftware() bool {
	if o != nil && o.VersaoSoftware.IsSet() {
		return true
	}

	return false
}

// SetVersaoSoftware gets a reference to the given NullableString and assigns it to the VersaoSoftware field.
func (o *GvmDTO) SetVersaoSoftware(v string) {
	o.VersaoSoftware.Set(&v)
}
// SetVersaoSoftwareNil sets the value for VersaoSoftware to be an explicit nil
func (o *GvmDTO) SetVersaoSoftwareNil() {
	o.VersaoSoftware.Set(nil)
}

// UnsetVersaoSoftware ensures that no value is present for VersaoSoftware, not even an explicit nil
func (o *GvmDTO) UnsetVersaoSoftware() {
	o.VersaoSoftware.Unset()
}

// GetUltimaComunicacao returns the UltimaComunicacao field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmDTO) GetUltimaComunicacao() time.Time {
	if o == nil || o.UltimaComunicacao.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.UltimaComunicacao.Get()
}

// GetUltimaComunicacaoOk returns a tuple with the UltimaComunicacao field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmDTO) GetUltimaComunicacaoOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.UltimaComunicacao.Get(), o.UltimaComunicacao.IsSet()
}

// HasUltimaComunicacao returns a boolean if a field has been set.
func (o *GvmDTO) HasUltimaComunicacao() bool {
	if o != nil && o.UltimaComunicacao.IsSet() {
		return true
	}

	return false
}

// SetUltimaComunicacao gets a reference to the given NullableTime and assigns it to the UltimaComunicacao field.
func (o *GvmDTO) SetUltimaComunicacao(v time.Time) {
	o.UltimaComunicacao.Set(&v)
}
// SetUltimaComunicacaoNil sets the value for UltimaComunicacao to be an explicit nil
func (o *GvmDTO) SetUltimaComunicacaoNil() {
	o.UltimaComunicacao.Set(nil)
}

// UnsetUltimaComunicacao ensures that no value is present for UltimaComunicacao, not even an explicit nil
func (o *GvmDTO) UnsetUltimaComunicacao() {
	o.UltimaComunicacao.Unset()
}

// GetRefLocal returns the RefLocal field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmDTO) GetRefLocal() int64 {
	if o == nil || o.RefLocal.Get() == nil {
		var ret int64
		return ret
	}
	return *o.RefLocal.Get()
}

// GetRefLocalOk returns a tuple with the RefLocal field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmDTO) GetRefLocalOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RefLocal.Get(), o.RefLocal.IsSet()
}

// HasRefLocal returns a boolean if a field has been set.
func (o *GvmDTO) HasRefLocal() bool {
	if o != nil && o.RefLocal.IsSet() {
		return true
	}

	return false
}

// SetRefLocal gets a reference to the given NullableInt64 and assigns it to the RefLocal field.
func (o *GvmDTO) SetRefLocal(v int64) {
	o.RefLocal.Set(&v)
}
// SetRefLocalNil sets the value for RefLocal to be an explicit nil
func (o *GvmDTO) SetRefLocalNil() {
	o.RefLocal.Set(nil)
}

// UnsetRefLocal ensures that no value is present for RefLocal, not even an explicit nil
func (o *GvmDTO) UnsetRefLocal() {
	o.RefLocal.Unset()
}

// GetRefEntidade returns the RefEntidade field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmDTO) GetRefEntidade() int64 {
	if o == nil || o.RefEntidade.Get() == nil {
		var ret int64
		return ret
	}
	return *o.RefEntidade.Get()
}

// GetRefEntidadeOk returns a tuple with the RefEntidade field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmDTO) GetRefEntidadeOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RefEntidade.Get(), o.RefEntidade.IsSet()
}

// HasRefEntidade returns a boolean if a field has been set.
func (o *GvmDTO) HasRefEntidade() bool {
	if o != nil && o.RefEntidade.IsSet() {
		return true
	}

	return false
}

// SetRefEntidade gets a reference to the given NullableInt64 and assigns it to the RefEntidade field.
func (o *GvmDTO) SetRefEntidade(v int64) {
	o.RefEntidade.Set(&v)
}
// SetRefEntidadeNil sets the value for RefEntidade to be an explicit nil
func (o *GvmDTO) SetRefEntidadeNil() {
	o.RefEntidade.Set(nil)
}

// UnsetRefEntidade ensures that no value is present for RefEntidade, not even an explicit nil
func (o *GvmDTO) UnsetRefEntidade() {
	o.RefEntidade.Unset()
}

// GetRefNo returns the RefNo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmDTO) GetRefNo() int64 {
	if o == nil || o.RefNo.Get() == nil {
		var ret int64
		return ret
	}
	return *o.RefNo.Get()
}

// GetRefNoOk returns a tuple with the RefNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmDTO) GetRefNoOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RefNo.Get(), o.RefNo.IsSet()
}

// HasRefNo returns a boolean if a field has been set.
func (o *GvmDTO) HasRefNo() bool {
	if o != nil && o.RefNo.IsSet() {
		return true
	}

	return false
}

// SetRefNo gets a reference to the given NullableInt64 and assigns it to the RefNo field.
func (o *GvmDTO) SetRefNo(v int64) {
	o.RefNo.Set(&v)
}
// SetRefNoNil sets the value for RefNo to be an explicit nil
func (o *GvmDTO) SetRefNoNil() {
	o.RefNo.Set(nil)
}

// UnsetRefNo ensures that no value is present for RefNo, not even an explicit nil
func (o *GvmDTO) UnsetRefNo() {
	o.RefNo.Unset()
}

// GetLatitude returns the Latitude field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmDTO) GetLatitude() string {
	if o == nil || o.Latitude.Get() == nil {
		var ret string
		return ret
	}
	return *o.Latitude.Get()
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmDTO) GetLatitudeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Latitude.Get(), o.Latitude.IsSet()
}

// HasLatitude returns a boolean if a field has been set.
func (o *GvmDTO) HasLatitude() bool {
	if o != nil && o.Latitude.IsSet() {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given NullableString and assigns it to the Latitude field.
func (o *GvmDTO) SetLatitude(v string) {
	o.Latitude.Set(&v)
}
// SetLatitudeNil sets the value for Latitude to be an explicit nil
func (o *GvmDTO) SetLatitudeNil() {
	o.Latitude.Set(nil)
}

// UnsetLatitude ensures that no value is present for Latitude, not even an explicit nil
func (o *GvmDTO) UnsetLatitude() {
	o.Latitude.Unset()
}

// GetLongitude returns the Longitude field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmDTO) GetLongitude() string {
	if o == nil || o.Longitude.Get() == nil {
		var ret string
		return ret
	}
	return *o.Longitude.Get()
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmDTO) GetLongitudeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Longitude.Get(), o.Longitude.IsSet()
}

// HasLongitude returns a boolean if a field has been set.
func (o *GvmDTO) HasLongitude() bool {
	if o != nil && o.Longitude.IsSet() {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given NullableString and assigns it to the Longitude field.
func (o *GvmDTO) SetLongitude(v string) {
	o.Longitude.Set(&v)
}
// SetLongitudeNil sets the value for Longitude to be an explicit nil
func (o *GvmDTO) SetLongitudeNil() {
	o.Longitude.Set(nil)
}

// UnsetLongitude ensures that no value is present for Longitude, not even an explicit nil
func (o *GvmDTO) UnsetLongitude() {
	o.Longitude.Unset()
}

// GetCompartimentos returns the Compartimentos field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmDTO) GetCompartimentos() []CompartimentoDTO {
	if o == nil  {
		var ret []CompartimentoDTO
		return ret
	}
	return o.Compartimentos
}

// GetCompartimentosOk returns a tuple with the Compartimentos field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmDTO) GetCompartimentosOk() (*[]CompartimentoDTO, bool) {
	if o == nil || o.Compartimentos == nil {
		return nil, false
	}
	return &o.Compartimentos, true
}

// HasCompartimentos returns a boolean if a field has been set.
func (o *GvmDTO) HasCompartimentos() bool {
	if o != nil && o.Compartimentos != nil {
		return true
	}

	return false
}

// SetCompartimentos gets a reference to the given []CompartimentoDTO and assigns it to the Compartimentos field.
func (o *GvmDTO) SetCompartimentos(v []CompartimentoDTO) {
	o.Compartimentos = v
}

// GetCompartimentosProduto returns the CompartimentosProduto field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmDTO) GetCompartimentosProduto() []ProdutoDTO {
	if o == nil  {
		var ret []ProdutoDTO
		return ret
	}
	return o.CompartimentosProduto
}

// GetCompartimentosProdutoOk returns a tuple with the CompartimentosProduto field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmDTO) GetCompartimentosProdutoOk() (*[]ProdutoDTO, bool) {
	if o == nil || o.CompartimentosProduto == nil {
		return nil, false
	}
	return &o.CompartimentosProduto, true
}

// HasCompartimentosProduto returns a boolean if a field has been set.
func (o *GvmDTO) HasCompartimentosProduto() bool {
	if o != nil && o.CompartimentosProduto != nil {
		return true
	}

	return false
}

// SetCompartimentosProduto gets a reference to the given []ProdutoDTO and assigns it to the CompartimentosProduto field.
func (o *GvmDTO) SetCompartimentosProduto(v []ProdutoDTO) {
	o.CompartimentosProduto = v
}

func (o GvmDTO) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Nome.IsSet() {
		toSerialize["nome"] = o.Nome.Get()
	}
	if o.Modelo.IsSet() {
		toSerialize["modelo"] = o.Modelo.Get()
	}
	if o.NumeroSerie.IsSet() {
		toSerialize["numeroSerie"] = o.NumeroSerie.Get()
	}
	if o.DataProducao.IsSet() {
		toSerialize["dataProducao"] = o.DataProducao.Get()
	}
	if o.VersaoFirmware.IsSet() {
		toSerialize["versaoFirmware"] = o.VersaoFirmware.Get()
	}
	if o.VersaoSoftware.IsSet() {
		toSerialize["versaoSoftware"] = o.VersaoSoftware.Get()
	}
	if o.UltimaComunicacao.IsSet() {
		toSerialize["ultimaComunicacao"] = o.UltimaComunicacao.Get()
	}
	if o.RefLocal.IsSet() {
		toSerialize["refLocal"] = o.RefLocal.Get()
	}
	if o.RefEntidade.IsSet() {
		toSerialize["refEntidade"] = o.RefEntidade.Get()
	}
	if o.RefNo.IsSet() {
		toSerialize["refNo"] = o.RefNo.Get()
	}
	if o.Latitude.IsSet() {
		toSerialize["latitude"] = o.Latitude.Get()
	}
	if o.Longitude.IsSet() {
		toSerialize["longitude"] = o.Longitude.Get()
	}
	if o.Compartimentos != nil {
		toSerialize["compartimentos"] = o.Compartimentos
	}
	if o.CompartimentosProduto != nil {
		toSerialize["compartimentosProduto"] = o.CompartimentosProduto
	}
	return json.Marshal(toSerialize)
}

type NullableGvmDTO struct {
	value *GvmDTO
	isSet bool
}

func (v NullableGvmDTO) Get() *GvmDTO {
	return v.value
}

func (v *NullableGvmDTO) Set(val *GvmDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableGvmDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableGvmDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGvmDTO(val *GvmDTO) *NullableGvmDTO {
	return &NullableGvmDTO{value: val, isSet: true}
}

func (v NullableGvmDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGvmDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


