/*
 * Petrolifera API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// TipoProduto the model 'TipoProduto'
type TipoProduto int32

// List of TipoProduto
const (
	_0 TipoProduto = 0
	_1 TipoProduto = 1
)

var allowedTipoProdutoEnumValues = []TipoProduto{
	0,
	1,
}

func (v *TipoProduto) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TipoProduto(value)
	for _, existing := range allowedTipoProdutoEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TipoProduto", value)
}

// NewTipoProdutoFromValue returns a pointer to a valid TipoProduto
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTipoProdutoFromValue(v int32) (*TipoProduto, error) {
	ev := TipoProduto(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TipoProduto: valid values are %v", v, allowedTipoProdutoEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TipoProduto) IsValid() bool {
	for _, existing := range allowedTipoProdutoEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TipoProduto value
func (v TipoProduto) Ptr() *TipoProduto {
	return &v
}

type NullableTipoProduto struct {
	value *TipoProduto
	isSet bool
}

func (v NullableTipoProduto) Get() *TipoProduto {
	return v.value
}

func (v *NullableTipoProduto) Set(val *TipoProduto) {
	v.value = val
	v.isSet = true
}

func (v NullableTipoProduto) IsSet() bool {
	return v.isSet
}

func (v *NullableTipoProduto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTipoProduto(val *TipoProduto) *NullableTipoProduto {
	return &NullableTipoProduto{value: val, isSet: true}
}

func (v NullableTipoProduto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTipoProduto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

