/*
 * Petrolifera API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// TipoOrdemServicoCompartimento the model 'TipoOrdemServicoCompartimento'
type TipoOrdemServicoCompartimento int32


var allowedTipoOrdemServicoCompartimentoEnumValues = []TipoOrdemServicoCompartimento{
	0,
	1,
}

func (v *TipoOrdemServicoCompartimento) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TipoOrdemServicoCompartimento(value)
	for _, existing := range allowedTipoOrdemServicoCompartimentoEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TipoOrdemServicoCompartimento", value)
}

// NewTipoOrdemServicoCompartimentoFromValue returns a pointer to a valid TipoOrdemServicoCompartimento
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTipoOrdemServicoCompartimentoFromValue(v int32) (*TipoOrdemServicoCompartimento, error) {
	ev := TipoOrdemServicoCompartimento(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TipoOrdemServicoCompartimento: valid values are %v", v, allowedTipoOrdemServicoCompartimentoEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TipoOrdemServicoCompartimento) IsValid() bool {
	for _, existing := range allowedTipoOrdemServicoCompartimentoEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TipoOrdemServicoCompartimento value
func (v TipoOrdemServicoCompartimento) Ptr() *TipoOrdemServicoCompartimento {
	return &v
}

type NullableTipoOrdemServicoCompartimento struct {
	value *TipoOrdemServicoCompartimento
	isSet bool
}

func (v NullableTipoOrdemServicoCompartimento) Get() *TipoOrdemServicoCompartimento {
	return v.value
}

func (v *NullableTipoOrdemServicoCompartimento) Set(val *TipoOrdemServicoCompartimento) {
	v.value = val
	v.isSet = true
}

func (v NullableTipoOrdemServicoCompartimento) IsSet() bool {
	return v.isSet
}

func (v *NullableTipoOrdemServicoCompartimento) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTipoOrdemServicoCompartimento(val *TipoOrdemServicoCompartimento) *NullableTipoOrdemServicoCompartimento {
	return &NullableTipoOrdemServicoCompartimento{value: val, isSet: true}
}

func (v NullableTipoOrdemServicoCompartimento) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTipoOrdemServicoCompartimento) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

