/*
 * Petrolifera API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// Fechadura struct for Fechadura
type Fechadura struct {
	Id *int64 `json:"id,omitempty"`
	Deleted *int32 `json:"deleted,omitempty"`
	Upd NullableTime `json:"upd,omitempty"`
	Usr NullableInt64 `json:"usr,omitempty"`
	RefCompartimento NullableInt64 `json:"refCompartimento,omitempty"`
	Endereco NullableString `json:"endereco,omitempty"`
	Canal NullableInt32 `json:"canal,omitempty"`
	Compartimento *Compartimento `json:"compartimento,omitempty"`
}

// NewFechadura instantiates a new Fechadura object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFechadura() *Fechadura {
	this := Fechadura{}
	return &this
}

// NewFechaduraWithDefaults instantiates a new Fechadura object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFechaduraWithDefaults() *Fechadura {
	this := Fechadura{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Fechadura) GetId() int64 {
	if o == nil || o.Id == nil {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fechadura) GetIdOk() (*int64, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Fechadura) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *Fechadura) SetId(v int64) {
	o.Id = &v
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *Fechadura) GetDeleted() int32 {
	if o == nil || o.Deleted == nil {
		var ret int32
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fechadura) GetDeletedOk() (*int32, bool) {
	if o == nil || o.Deleted == nil {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *Fechadura) HasDeleted() bool {
	if o != nil && o.Deleted != nil {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given int32 and assigns it to the Deleted field.
func (o *Fechadura) SetDeleted(v int32) {
	o.Deleted = &v
}

// GetUpd returns the Upd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Fechadura) GetUpd() time.Time {
	if o == nil || o.Upd.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.Upd.Get()
}

// GetUpdOk returns a tuple with the Upd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Fechadura) GetUpdOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Upd.Get(), o.Upd.IsSet()
}

// HasUpd returns a boolean if a field has been set.
func (o *Fechadura) HasUpd() bool {
	if o != nil && o.Upd.IsSet() {
		return true
	}

	return false
}

// SetUpd gets a reference to the given NullableTime and assigns it to the Upd field.
func (o *Fechadura) SetUpd(v time.Time) {
	o.Upd.Set(&v)
}
// SetUpdNil sets the value for Upd to be an explicit nil
func (o *Fechadura) SetUpdNil() {
	o.Upd.Set(nil)
}

// UnsetUpd ensures that no value is present for Upd, not even an explicit nil
func (o *Fechadura) UnsetUpd() {
	o.Upd.Unset()
}

// GetUsr returns the Usr field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Fechadura) GetUsr() int64 {
	if o == nil || o.Usr.Get() == nil {
		var ret int64
		return ret
	}
	return *o.Usr.Get()
}

// GetUsrOk returns a tuple with the Usr field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Fechadura) GetUsrOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Usr.Get(), o.Usr.IsSet()
}

// HasUsr returns a boolean if a field has been set.
func (o *Fechadura) HasUsr() bool {
	if o != nil && o.Usr.IsSet() {
		return true
	}

	return false
}

// SetUsr gets a reference to the given NullableInt64 and assigns it to the Usr field.
func (o *Fechadura) SetUsr(v int64) {
	o.Usr.Set(&v)
}
// SetUsrNil sets the value for Usr to be an explicit nil
func (o *Fechadura) SetUsrNil() {
	o.Usr.Set(nil)
}

// UnsetUsr ensures that no value is present for Usr, not even an explicit nil
func (o *Fechadura) UnsetUsr() {
	o.Usr.Unset()
}

// GetRefCompartimento returns the RefCompartimento field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Fechadura) GetRefCompartimento() int64 {
	if o == nil || o.RefCompartimento.Get() == nil {
		var ret int64
		return ret
	}
	return *o.RefCompartimento.Get()
}

// GetRefCompartimentoOk returns a tuple with the RefCompartimento field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Fechadura) GetRefCompartimentoOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RefCompartimento.Get(), o.RefCompartimento.IsSet()
}

// HasRefCompartimento returns a boolean if a field has been set.
func (o *Fechadura) HasRefCompartimento() bool {
	if o != nil && o.RefCompartimento.IsSet() {
		return true
	}

	return false
}

// SetRefCompartimento gets a reference to the given NullableInt64 and assigns it to the RefCompartimento field.
func (o *Fechadura) SetRefCompartimento(v int64) {
	o.RefCompartimento.Set(&v)
}
// SetRefCompartimentoNil sets the value for RefCompartimento to be an explicit nil
func (o *Fechadura) SetRefCompartimentoNil() {
	o.RefCompartimento.Set(nil)
}

// UnsetRefCompartimento ensures that no value is present for RefCompartimento, not even an explicit nil
func (o *Fechadura) UnsetRefCompartimento() {
	o.RefCompartimento.Unset()
}

// GetEndereco returns the Endereco field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Fechadura) GetEndereco() string {
	if o == nil || o.Endereco.Get() == nil {
		var ret string
		return ret
	}
	return *o.Endereco.Get()
}

// GetEnderecoOk returns a tuple with the Endereco field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Fechadura) GetEnderecoOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Endereco.Get(), o.Endereco.IsSet()
}

// HasEndereco returns a boolean if a field has been set.
func (o *Fechadura) HasEndereco() bool {
	if o != nil && o.Endereco.IsSet() {
		return true
	}

	return false
}

// SetEndereco gets a reference to the given NullableString and assigns it to the Endereco field.
func (o *Fechadura) SetEndereco(v string) {
	o.Endereco.Set(&v)
}
// SetEnderecoNil sets the value for Endereco to be an explicit nil
func (o *Fechadura) SetEnderecoNil() {
	o.Endereco.Set(nil)
}

// UnsetEndereco ensures that no value is present for Endereco, not even an explicit nil
func (o *Fechadura) UnsetEndereco() {
	o.Endereco.Unset()
}

// GetCanal returns the Canal field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Fechadura) GetCanal() int32 {
	if o == nil || o.Canal.Get() == nil {
		var ret int32
		return ret
	}
	return *o.Canal.Get()
}

// GetCanalOk returns a tuple with the Canal field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Fechadura) GetCanalOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Canal.Get(), o.Canal.IsSet()
}

// HasCanal returns a boolean if a field has been set.
func (o *Fechadura) HasCanal() bool {
	if o != nil && o.Canal.IsSet() {
		return true
	}

	return false
}

// SetCanal gets a reference to the given NullableInt32 and assigns it to the Canal field.
func (o *Fechadura) SetCanal(v int32) {
	o.Canal.Set(&v)
}
// SetCanalNil sets the value for Canal to be an explicit nil
func (o *Fechadura) SetCanalNil() {
	o.Canal.Set(nil)
}

// UnsetCanal ensures that no value is present for Canal, not even an explicit nil
func (o *Fechadura) UnsetCanal() {
	o.Canal.Unset()
}

// GetCompartimento returns the Compartimento field value if set, zero value otherwise.
func (o *Fechadura) GetCompartimento() Compartimento {
	if o == nil || o.Compartimento == nil {
		var ret Compartimento
		return ret
	}
	return *o.Compartimento
}

// GetCompartimentoOk returns a tuple with the Compartimento field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fechadura) GetCompartimentoOk() (*Compartimento, bool) {
	if o == nil || o.Compartimento == nil {
		return nil, false
	}
	return o.Compartimento, true
}

// HasCompartimento returns a boolean if a field has been set.
func (o *Fechadura) HasCompartimento() bool {
	if o != nil && o.Compartimento != nil {
		return true
	}

	return false
}

// SetCompartimento gets a reference to the given Compartimento and assigns it to the Compartimento field.
func (o *Fechadura) SetCompartimento(v Compartimento) {
	o.Compartimento = &v
}

func (o Fechadura) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Deleted != nil {
		toSerialize["deleted"] = o.Deleted
	}
	if o.Upd.IsSet() {
		toSerialize["upd"] = o.Upd.Get()
	}
	if o.Usr.IsSet() {
		toSerialize["usr"] = o.Usr.Get()
	}
	if o.RefCompartimento.IsSet() {
		toSerialize["refCompartimento"] = o.RefCompartimento.Get()
	}
	if o.Endereco.IsSet() {
		toSerialize["endereco"] = o.Endereco.Get()
	}
	if o.Canal.IsSet() {
		toSerialize["canal"] = o.Canal.Get()
	}
	if o.Compartimento != nil {
		toSerialize["compartimento"] = o.Compartimento
	}
	return json.Marshal(toSerialize)
}

type NullableFechadura struct {
	value *Fechadura
	isSet bool
}

func (v NullableFechadura) Get() *Fechadura {
	return v.value
}

func (v *NullableFechadura) Set(val *Fechadura) {
	v.value = val
	v.isSet = true
}

func (v NullableFechadura) IsSet() bool {
	return v.isSet
}

func (v *NullableFechadura) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFechadura(val *Fechadura) *NullableFechadura {
	return &NullableFechadura{value: val, isSet: true}
}

func (v NullableFechadura) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFechadura) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


