/*
 * Petrolifera API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// GvmVM struct for GvmVM
type GvmVM struct {
	Nome NullableString `json:"nome,omitempty"`
	Modelo NullableString `json:"modelo,omitempty"`
	NumeroSerie NullableString `json:"numeroSerie,omitempty"`
	DataProducao NullableTime `json:"dataProducao,omitempty"`
	VersaoFirmware NullableString `json:"versaoFirmware,omitempty"`
	VersaoSoftware NullableString `json:"versaoSoftware,omitempty"`
	UltimaComunicacao NullableTime `json:"ultimaComunicacao,omitempty"`
	RefLocal NullableInt64 `json:"refLocal,omitempty"`
	RefEntidade NullableInt64 `json:"refEntidade,omitempty"`
	RefNo NullableInt64 `json:"refNo,omitempty"`
	Latitude NullableString `json:"latitude,omitempty"`
	Longitude NullableString `json:"longitude,omitempty"`
}

// NewGvmVM instantiates a new GvmVM object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGvmVM() *GvmVM {
	this := GvmVM{}
	return &this
}

// NewGvmVMWithDefaults instantiates a new GvmVM object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGvmVMWithDefaults() *GvmVM {
	this := GvmVM{}
	return &this
}

// GetNome returns the Nome field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmVM) GetNome() string {
	if o == nil || o.Nome.Get() == nil {
		var ret string
		return ret
	}
	return *o.Nome.Get()
}

// GetNomeOk returns a tuple with the Nome field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmVM) GetNomeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Nome.Get(), o.Nome.IsSet()
}

// HasNome returns a boolean if a field has been set.
func (o *GvmVM) HasNome() bool {
	if o != nil && o.Nome.IsSet() {
		return true
	}

	return false
}

// SetNome gets a reference to the given NullableString and assigns it to the Nome field.
func (o *GvmVM) SetNome(v string) {
	o.Nome.Set(&v)
}
// SetNomeNil sets the value for Nome to be an explicit nil
func (o *GvmVM) SetNomeNil() {
	o.Nome.Set(nil)
}

// UnsetNome ensures that no value is present for Nome, not even an explicit nil
func (o *GvmVM) UnsetNome() {
	o.Nome.Unset()
}

// GetModelo returns the Modelo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmVM) GetModelo() string {
	if o == nil || o.Modelo.Get() == nil {
		var ret string
		return ret
	}
	return *o.Modelo.Get()
}

// GetModeloOk returns a tuple with the Modelo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmVM) GetModeloOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Modelo.Get(), o.Modelo.IsSet()
}

// HasModelo returns a boolean if a field has been set.
func (o *GvmVM) HasModelo() bool {
	if o != nil && o.Modelo.IsSet() {
		return true
	}

	return false
}

// SetModelo gets a reference to the given NullableString and assigns it to the Modelo field.
func (o *GvmVM) SetModelo(v string) {
	o.Modelo.Set(&v)
}
// SetModeloNil sets the value for Modelo to be an explicit nil
func (o *GvmVM) SetModeloNil() {
	o.Modelo.Set(nil)
}

// UnsetModelo ensures that no value is present for Modelo, not even an explicit nil
func (o *GvmVM) UnsetModelo() {
	o.Modelo.Unset()
}

// GetNumeroSerie returns the NumeroSerie field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmVM) GetNumeroSerie() string {
	if o == nil || o.NumeroSerie.Get() == nil {
		var ret string
		return ret
	}
	return *o.NumeroSerie.Get()
}

// GetNumeroSerieOk returns a tuple with the NumeroSerie field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmVM) GetNumeroSerieOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.NumeroSerie.Get(), o.NumeroSerie.IsSet()
}

// HasNumeroSerie returns a boolean if a field has been set.
func (o *GvmVM) HasNumeroSerie() bool {
	if o != nil && o.NumeroSerie.IsSet() {
		return true
	}

	return false
}

// SetNumeroSerie gets a reference to the given NullableString and assigns it to the NumeroSerie field.
func (o *GvmVM) SetNumeroSerie(v string) {
	o.NumeroSerie.Set(&v)
}
// SetNumeroSerieNil sets the value for NumeroSerie to be an explicit nil
func (o *GvmVM) SetNumeroSerieNil() {
	o.NumeroSerie.Set(nil)
}

// UnsetNumeroSerie ensures that no value is present for NumeroSerie, not even an explicit nil
func (o *GvmVM) UnsetNumeroSerie() {
	o.NumeroSerie.Unset()
}

// GetDataProducao returns the DataProducao field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmVM) GetDataProducao() time.Time {
	if o == nil || o.DataProducao.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.DataProducao.Get()
}

// GetDataProducaoOk returns a tuple with the DataProducao field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmVM) GetDataProducaoOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.DataProducao.Get(), o.DataProducao.IsSet()
}

// HasDataProducao returns a boolean if a field has been set.
func (o *GvmVM) HasDataProducao() bool {
	if o != nil && o.DataProducao.IsSet() {
		return true
	}

	return false
}

// SetDataProducao gets a reference to the given NullableTime and assigns it to the DataProducao field.
func (o *GvmVM) SetDataProducao(v time.Time) {
	o.DataProducao.Set(&v)
}
// SetDataProducaoNil sets the value for DataProducao to be an explicit nil
func (o *GvmVM) SetDataProducaoNil() {
	o.DataProducao.Set(nil)
}

// UnsetDataProducao ensures that no value is present for DataProducao, not even an explicit nil
func (o *GvmVM) UnsetDataProducao() {
	o.DataProducao.Unset()
}

// GetVersaoFirmware returns the VersaoFirmware field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmVM) GetVersaoFirmware() string {
	if o == nil || o.VersaoFirmware.Get() == nil {
		var ret string
		return ret
	}
	return *o.VersaoFirmware.Get()
}

// GetVersaoFirmwareOk returns a tuple with the VersaoFirmware field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmVM) GetVersaoFirmwareOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.VersaoFirmware.Get(), o.VersaoFirmware.IsSet()
}

// HasVersaoFirmware returns a boolean if a field has been set.
func (o *GvmVM) HasVersaoFirmware() bool {
	if o != nil && o.VersaoFirmware.IsSet() {
		return true
	}

	return false
}

// SetVersaoFirmware gets a reference to the given NullableString and assigns it to the VersaoFirmware field.
func (o *GvmVM) SetVersaoFirmware(v string) {
	o.VersaoFirmware.Set(&v)
}
// SetVersaoFirmwareNil sets the value for VersaoFirmware to be an explicit nil
func (o *GvmVM) SetVersaoFirmwareNil() {
	o.VersaoFirmware.Set(nil)
}

// UnsetVersaoFirmware ensures that no value is present for VersaoFirmware, not even an explicit nil
func (o *GvmVM) UnsetVersaoFirmware() {
	o.VersaoFirmware.Unset()
}

// GetVersaoSoftware returns the VersaoSoftware field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmVM) GetVersaoSoftware() string {
	if o == nil || o.VersaoSoftware.Get() == nil {
		var ret string
		return ret
	}
	return *o.VersaoSoftware.Get()
}

// GetVersaoSoftwareOk returns a tuple with the VersaoSoftware field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmVM) GetVersaoSoftwareOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.VersaoSoftware.Get(), o.VersaoSoftware.IsSet()
}

// HasVersaoSoftware returns a boolean if a field has been set.
func (o *GvmVM) HasVersaoSoftware() bool {
	if o != nil && o.VersaoSoftware.IsSet() {
		return true
	}

	return false
}

// SetVersaoSoftware gets a reference to the given NullableString and assigns it to the VersaoSoftware field.
func (o *GvmVM) SetVersaoSoftware(v string) {
	o.VersaoSoftware.Set(&v)
}
// SetVersaoSoftwareNil sets the value for VersaoSoftware to be an explicit nil
func (o *GvmVM) SetVersaoSoftwareNil() {
	o.VersaoSoftware.Set(nil)
}

// UnsetVersaoSoftware ensures that no value is present for VersaoSoftware, not even an explicit nil
func (o *GvmVM) UnsetVersaoSoftware() {
	o.VersaoSoftware.Unset()
}

// GetUltimaComunicacao returns the UltimaComunicacao field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmVM) GetUltimaComunicacao() time.Time {
	if o == nil || o.UltimaComunicacao.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.UltimaComunicacao.Get()
}

// GetUltimaComunicacaoOk returns a tuple with the UltimaComunicacao field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmVM) GetUltimaComunicacaoOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.UltimaComunicacao.Get(), o.UltimaComunicacao.IsSet()
}

// HasUltimaComunicacao returns a boolean if a field has been set.
func (o *GvmVM) HasUltimaComunicacao() bool {
	if o != nil && o.UltimaComunicacao.IsSet() {
		return true
	}

	return false
}

// SetUltimaComunicacao gets a reference to the given NullableTime and assigns it to the UltimaComunicacao field.
func (o *GvmVM) SetUltimaComunicacao(v time.Time) {
	o.UltimaComunicacao.Set(&v)
}
// SetUltimaComunicacaoNil sets the value for UltimaComunicacao to be an explicit nil
func (o *GvmVM) SetUltimaComunicacaoNil() {
	o.UltimaComunicacao.Set(nil)
}

// UnsetUltimaComunicacao ensures that no value is present for UltimaComunicacao, not even an explicit nil
func (o *GvmVM) UnsetUltimaComunicacao() {
	o.UltimaComunicacao.Unset()
}

// GetRefLocal returns the RefLocal field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmVM) GetRefLocal() int64 {
	if o == nil || o.RefLocal.Get() == nil {
		var ret int64
		return ret
	}
	return *o.RefLocal.Get()
}

// GetRefLocalOk returns a tuple with the RefLocal field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmVM) GetRefLocalOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RefLocal.Get(), o.RefLocal.IsSet()
}

// HasRefLocal returns a boolean if a field has been set.
func (o *GvmVM) HasRefLocal() bool {
	if o != nil && o.RefLocal.IsSet() {
		return true
	}

	return false
}

// SetRefLocal gets a reference to the given NullableInt64 and assigns it to the RefLocal field.
func (o *GvmVM) SetRefLocal(v int64) {
	o.RefLocal.Set(&v)
}
// SetRefLocalNil sets the value for RefLocal to be an explicit nil
func (o *GvmVM) SetRefLocalNil() {
	o.RefLocal.Set(nil)
}

// UnsetRefLocal ensures that no value is present for RefLocal, not even an explicit nil
func (o *GvmVM) UnsetRefLocal() {
	o.RefLocal.Unset()
}

// GetRefEntidade returns the RefEntidade field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmVM) GetRefEntidade() int64 {
	if o == nil || o.RefEntidade.Get() == nil {
		var ret int64
		return ret
	}
	return *o.RefEntidade.Get()
}

// GetRefEntidadeOk returns a tuple with the RefEntidade field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmVM) GetRefEntidadeOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RefEntidade.Get(), o.RefEntidade.IsSet()
}

// HasRefEntidade returns a boolean if a field has been set.
func (o *GvmVM) HasRefEntidade() bool {
	if o != nil && o.RefEntidade.IsSet() {
		return true
	}

	return false
}

// SetRefEntidade gets a reference to the given NullableInt64 and assigns it to the RefEntidade field.
func (o *GvmVM) SetRefEntidade(v int64) {
	o.RefEntidade.Set(&v)
}
// SetRefEntidadeNil sets the value for RefEntidade to be an explicit nil
func (o *GvmVM) SetRefEntidadeNil() {
	o.RefEntidade.Set(nil)
}

// UnsetRefEntidade ensures that no value is present for RefEntidade, not even an explicit nil
func (o *GvmVM) UnsetRefEntidade() {
	o.RefEntidade.Unset()
}

// GetRefNo returns the RefNo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmVM) GetRefNo() int64 {
	if o == nil || o.RefNo.Get() == nil {
		var ret int64
		return ret
	}
	return *o.RefNo.Get()
}

// GetRefNoOk returns a tuple with the RefNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmVM) GetRefNoOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RefNo.Get(), o.RefNo.IsSet()
}

// HasRefNo returns a boolean if a field has been set.
func (o *GvmVM) HasRefNo() bool {
	if o != nil && o.RefNo.IsSet() {
		return true
	}

	return false
}

// SetRefNo gets a reference to the given NullableInt64 and assigns it to the RefNo field.
func (o *GvmVM) SetRefNo(v int64) {
	o.RefNo.Set(&v)
}
// SetRefNoNil sets the value for RefNo to be an explicit nil
func (o *GvmVM) SetRefNoNil() {
	o.RefNo.Set(nil)
}

// UnsetRefNo ensures that no value is present for RefNo, not even an explicit nil
func (o *GvmVM) UnsetRefNo() {
	o.RefNo.Unset()
}

// GetLatitude returns the Latitude field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmVM) GetLatitude() string {
	if o == nil || o.Latitude.Get() == nil {
		var ret string
		return ret
	}
	return *o.Latitude.Get()
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmVM) GetLatitudeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Latitude.Get(), o.Latitude.IsSet()
}

// HasLatitude returns a boolean if a field has been set.
func (o *GvmVM) HasLatitude() bool {
	if o != nil && o.Latitude.IsSet() {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given NullableString and assigns it to the Latitude field.
func (o *GvmVM) SetLatitude(v string) {
	o.Latitude.Set(&v)
}
// SetLatitudeNil sets the value for Latitude to be an explicit nil
func (o *GvmVM) SetLatitudeNil() {
	o.Latitude.Set(nil)
}

// UnsetLatitude ensures that no value is present for Latitude, not even an explicit nil
func (o *GvmVM) UnsetLatitude() {
	o.Latitude.Unset()
}

// GetLongitude returns the Longitude field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GvmVM) GetLongitude() string {
	if o == nil || o.Longitude.Get() == nil {
		var ret string
		return ret
	}
	return *o.Longitude.Get()
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GvmVM) GetLongitudeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Longitude.Get(), o.Longitude.IsSet()
}

// HasLongitude returns a boolean if a field has been set.
func (o *GvmVM) HasLongitude() bool {
	if o != nil && o.Longitude.IsSet() {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given NullableString and assigns it to the Longitude field.
func (o *GvmVM) SetLongitude(v string) {
	o.Longitude.Set(&v)
}
// SetLongitudeNil sets the value for Longitude to be an explicit nil
func (o *GvmVM) SetLongitudeNil() {
	o.Longitude.Set(nil)
}

// UnsetLongitude ensures that no value is present for Longitude, not even an explicit nil
func (o *GvmVM) UnsetLongitude() {
	o.Longitude.Unset()
}

func (o GvmVM) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Nome.IsSet() {
		toSerialize["nome"] = o.Nome.Get()
	}
	if o.Modelo.IsSet() {
		toSerialize["modelo"] = o.Modelo.Get()
	}
	if o.NumeroSerie.IsSet() {
		toSerialize["numeroSerie"] = o.NumeroSerie.Get()
	}
	if o.DataProducao.IsSet() {
		toSerialize["dataProducao"] = o.DataProducao.Get()
	}
	if o.VersaoFirmware.IsSet() {
		toSerialize["versaoFirmware"] = o.VersaoFirmware.Get()
	}
	if o.VersaoSoftware.IsSet() {
		toSerialize["versaoSoftware"] = o.VersaoSoftware.Get()
	}
	if o.UltimaComunicacao.IsSet() {
		toSerialize["ultimaComunicacao"] = o.UltimaComunicacao.Get()
	}
	if o.RefLocal.IsSet() {
		toSerialize["refLocal"] = o.RefLocal.Get()
	}
	if o.RefEntidade.IsSet() {
		toSerialize["refEntidade"] = o.RefEntidade.Get()
	}
	if o.RefNo.IsSet() {
		toSerialize["refNo"] = o.RefNo.Get()
	}
	if o.Latitude.IsSet() {
		toSerialize["latitude"] = o.Latitude.Get()
	}
	if o.Longitude.IsSet() {
		toSerialize["longitude"] = o.Longitude.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableGvmVM struct {
	value *GvmVM
	isSet bool
}

func (v NullableGvmVM) Get() *GvmVM {
	return v.value
}

func (v *NullableGvmVM) Set(val *GvmVM) {
	v.value = val
	v.isSet = true
}

func (v NullableGvmVM) IsSet() bool {
	return v.isSet
}

func (v *NullableGvmVM) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGvmVM(val *GvmVM) *NullableGvmVM {
	return &NullableGvmVM{value: val, isSet: true}
}

func (v NullableGvmVM) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGvmVM) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


