/*
 * Petrolifera API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// UtilizadorEstados the model 'UtilizadorEstados'
type UtilizadorEstados int32

// List of UtilizadorEstados
const (
	_0 UtilizadorEstados = 0
	_1 UtilizadorEstados = 1
)

var allowedUtilizadorEstadosEnumValues = []UtilizadorEstados{
	0,
	1,
}

func (v *UtilizadorEstados) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := UtilizadorEstados(value)
	for _, existing := range allowedUtilizadorEstadosEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid UtilizadorEstados", value)
}

// NewUtilizadorEstadosFromValue returns a pointer to a valid UtilizadorEstados
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewUtilizadorEstadosFromValue(v int32) (*UtilizadorEstados, error) {
	ev := UtilizadorEstados(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for UtilizadorEstados: valid values are %v", v, allowedUtilizadorEstadosEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v UtilizadorEstados) IsValid() bool {
	for _, existing := range allowedUtilizadorEstadosEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to UtilizadorEstados value
func (v UtilizadorEstados) Ptr() *UtilizadorEstados {
	return &v
}

type NullableUtilizadorEstados struct {
	value *UtilizadorEstados
	isSet bool
}

func (v NullableUtilizadorEstados) Get() *UtilizadorEstados {
	return v.value
}

func (v *NullableUtilizadorEstados) Set(val *UtilizadorEstados) {
	v.value = val
	v.isSet = true
}

func (v NullableUtilizadorEstados) IsSet() bool {
	return v.isSet
}

func (v *NullableUtilizadorEstados) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUtilizadorEstados(val *UtilizadorEstados) *NullableUtilizadorEstados {
	return &NullableUtilizadorEstados{value: val, isSet: true}
}

func (v NullableUtilizadorEstados) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUtilizadorEstados) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

