/*
 * Petrolifera API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AberturaOrdemServico struct for AberturaOrdemServico
type AberturaOrdemServico struct {
	RefOrdemServico NullableInt64 `json:"refOrdemServico,omitempty"`
	ListaRecolha []OSCompartimentoProduto `json:"listaRecolha,omitempty"`
	ListaDeposito []OSCompartimentoProduto `json:"listaDeposito,omitempty"`
}

// NewAberturaOrdemServico instantiates a new AberturaOrdemServico object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAberturaOrdemServico() *AberturaOrdemServico {
	this := AberturaOrdemServico{}
	return &this
}

// NewAberturaOrdemServicoWithDefaults instantiates a new AberturaOrdemServico object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAberturaOrdemServicoWithDefaults() *AberturaOrdemServico {
	this := AberturaOrdemServico{}
	return &this
}

// GetRefOrdemServico returns the RefOrdemServico field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AberturaOrdemServico) GetRefOrdemServico() int64 {
	if o == nil || o.RefOrdemServico.Get() == nil {
		var ret int64
		return ret
	}
	return *o.RefOrdemServico.Get()
}

// GetRefOrdemServicoOk returns a tuple with the RefOrdemServico field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AberturaOrdemServico) GetRefOrdemServicoOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RefOrdemServico.Get(), o.RefOrdemServico.IsSet()
}

// HasRefOrdemServico returns a boolean if a field has been set.
func (o *AberturaOrdemServico) HasRefOrdemServico() bool {
	if o != nil && o.RefOrdemServico.IsSet() {
		return true
	}

	return false
}

// SetRefOrdemServico gets a reference to the given NullableInt64 and assigns it to the RefOrdemServico field.
func (o *AberturaOrdemServico) SetRefOrdemServico(v int64) {
	o.RefOrdemServico.Set(&v)
}
// SetRefOrdemServicoNil sets the value for RefOrdemServico to be an explicit nil
func (o *AberturaOrdemServico) SetRefOrdemServicoNil() {
	o.RefOrdemServico.Set(nil)
}

// UnsetRefOrdemServico ensures that no value is present for RefOrdemServico, not even an explicit nil
func (o *AberturaOrdemServico) UnsetRefOrdemServico() {
	o.RefOrdemServico.Unset()
}

// GetListaRecolha returns the ListaRecolha field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AberturaOrdemServico) GetListaRecolha() []OSCompartimentoProduto {
	if o == nil  {
		var ret []OSCompartimentoProduto
		return ret
	}
	return o.ListaRecolha
}

// GetListaRecolhaOk returns a tuple with the ListaRecolha field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AberturaOrdemServico) GetListaRecolhaOk() (*[]OSCompartimentoProduto, bool) {
	if o == nil || o.ListaRecolha == nil {
		return nil, false
	}
	return &o.ListaRecolha, true
}

// HasListaRecolha returns a boolean if a field has been set.
func (o *AberturaOrdemServico) HasListaRecolha() bool {
	if o != nil && o.ListaRecolha != nil {
		return true
	}

	return false
}

// SetListaRecolha gets a reference to the given []OSCompartimentoProduto and assigns it to the ListaRecolha field.
func (o *AberturaOrdemServico) SetListaRecolha(v []OSCompartimentoProduto) {
	o.ListaRecolha = v
}

// GetListaDeposito returns the ListaDeposito field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AberturaOrdemServico) GetListaDeposito() []OSCompartimentoProduto {
	if o == nil  {
		var ret []OSCompartimentoProduto
		return ret
	}
	return o.ListaDeposito
}

// GetListaDepositoOk returns a tuple with the ListaDeposito field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AberturaOrdemServico) GetListaDepositoOk() (*[]OSCompartimentoProduto, bool) {
	if o == nil || o.ListaDeposito == nil {
		return nil, false
	}
	return &o.ListaDeposito, true
}

// HasListaDeposito returns a boolean if a field has been set.
func (o *AberturaOrdemServico) HasListaDeposito() bool {
	if o != nil && o.ListaDeposito != nil {
		return true
	}

	return false
}

// SetListaDeposito gets a reference to the given []OSCompartimentoProduto and assigns it to the ListaDeposito field.
func (o *AberturaOrdemServico) SetListaDeposito(v []OSCompartimentoProduto) {
	o.ListaDeposito = v
}

func (o AberturaOrdemServico) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.RefOrdemServico.IsSet() {
		toSerialize["refOrdemServico"] = o.RefOrdemServico.Get()
	}
	if o.ListaRecolha != nil {
		toSerialize["listaRecolha"] = o.ListaRecolha
	}
	if o.ListaDeposito != nil {
		toSerialize["listaDeposito"] = o.ListaDeposito
	}
	return json.Marshal(toSerialize)
}

type NullableAberturaOrdemServico struct {
	value *AberturaOrdemServico
	isSet bool
}

func (v NullableAberturaOrdemServico) Get() *AberturaOrdemServico {
	return v.value
}

func (v *NullableAberturaOrdemServico) Set(val *AberturaOrdemServico) {
	v.value = val
	v.isSet = true
}

func (v NullableAberturaOrdemServico) IsSet() bool {
	return v.isSet
}

func (v *NullableAberturaOrdemServico) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAberturaOrdemServico(val *AberturaOrdemServico) *NullableAberturaOrdemServico {
	return &NullableAberturaOrdemServico{value: val, isSet: true}
}

func (v NullableAberturaOrdemServico) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAberturaOrdemServico) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


